---
- name: Ensuring hosts good behavior
  hosts: all
  gather_facts: yes
  tasks:
    - name: Looking for dnsmasq process
      command: pgrep dnsmasq
      changed_when: false

- name: Ensuring containers creation, connection and good behavior
  hosts: all_containers
  gather_facts: yes
  tasks:
    - name: Gather additional facts
      setup:
        gather_subset: "!all,network"
        filter: ansible_interfaces
      delegate_to: "{{ physical_host }}"
      delegate_facts: true

    - name: Ensure the physical host has all the proper interfaces defined
      assert:
        that:
          - item.value.bridge in hostvars[physical_host]['ansible_facts']['interfaces']
      with_dict: "{{ container_networks }}"

    - name: Check if dns resolution and external connectivity is fine
      get_url:
        url: https://opendev.org/openstack/openstack-ansible/raw/ansible-role-requirements.yml
        dest: /tmp/osa-master-requirements
      environment: "{{ deployment_environment_variables | default({}) }}"
