---
- hosts: all
  - tasks:
      name: install packages
      become: true
      become_user: root
      
      become_pass: ubuntu
      
      apt:
        state: present
        name:
          - htop
