---
- hosts: all
  tasks:
    - name: install packages
      become: true
      become_user: root
      
      ansible_become_pass: ubuntu
      
      apt:
        state: present
        name:
         - wget
