---
- hosts: all
  tasks:
    - name: install packages
      become_user: root
      become: true
        vars_files:
         - secret
      apt:
        state: present
        name:
         - htop
