---
- hosts: all
  tasks:
    - name: install htop
      become_user: root
      ansible_password: '{{ lookup("env", "ANSIPASS") }}'
      become: true
      apt:
        state: present
        name:
         - htop 
